//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FazendaUrbanaDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class os
    {
        public int id { get; set; }
        public System.DateTime dateEmi { get; set; }
        public Nullable<System.DateTime> entregaProd { get; set; }
        public string clientCpf { get; set; }
        public int employeeId { get; set; }
        public int productId { get; set; }
        public int quantity { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual employees employees { get; set; }
        public virtual products products { get; set; }
    }
}
